services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8055:8055"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./extensions:/app/extensions
    env_file:
      - .env
    command: npm start
